repos:
  - repo: local
    hooks:
      - id: nox
        name: Nox
        entry: nox
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
        verbose: true
        always_run: true