repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

    -   id: black
        name: black
        entry: black
        language: system
        types: [python]

    -   id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]

    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--disable=W0511]

    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
