name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  FORCE_COLOR: "3"

jobs:
  docs:
    uses: ./.github/workflows/publish-docs.yml
  publish:
    uses: ./.github/workflows/publish-to-pypi.yml
