name: Publish to TestPypi

on:
  # Creates a reusable workflow
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/buildwheel.yml
  test-publish:
    name: Publish to TestPyPI
    needs: [build]
    permissions:
      id-token: write
    environment: test-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
